[tox]
env_list = py310, py311, py312, py313, py314
isolated_build = true
skip_missing_interpreters = true

[testenv]
description = Run unit tests
install_command = python -I -m pip install -c {toxinidir}/constraints.txt {opts} {packages}
extras = test
commands = pytest {posargs}

[testenv:docs]
description = Build Sphinx documentation
extras = docs
commands = sphinx-build -d {toxworkdir}/doctrees -b html docs {toxworkdir}/site

[testenv:build]
description = Build source and wheel distributions
extras = build
commands =
    python -m build
    python -m twine check dist/*
